### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by timkoers**
Added net argument and ulimits argument.

Untested, so I hope that the unit test run.

### CODE REVIEW

**Comment by magicmark** [comment]
Thanks for this @timkoers!

Looks there there was a test failure :(  https://travis-ci.org/github/magicmark/composerize/builds/678928371

(not sure why it's not being linked here, will look into that...)

**Comment by timkoers** [comment]
Thanks! That would be great :-)

**Comment by magicmark** [comment]
@timkoers fixed!

**Comment by timkoers** [comment]
Great! There was another option that was missing, well missing..
The network option allows for a shorter command called net, did you implement that too?

**Comment by magicmark** [comment]
Yep! Try it out http://composerize.com/

**Comment by timkoers** [comment]
It doesn't seem to work! 
-net host adds
environment:
            - 'true'
and --net=host doesn't do anything

**Comment by magicmark** [comment]
@timkoers works for me? try clearing your cache?

https://i.fluffy.cc/XzFHgGN88PBkpRR4jpVL7t3sSXk3KJgD.png

**Comment by timkoers** [comment]
Good call! It's working :)

**Pull request closed without merging**
